name: Deploy to gh-pages

permissions: {}

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: PROTECTED-ENV # Specify the environment to use
    permissions:
      packages: read

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (optional, if you need to build something)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install published package
        run: npm install @sit-devex-test-org/cowsays-be-safe --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy latest package
        run: |
          cat node_modules/@sit-devex-test-org/cowsays-be-safe/package.json
          cp node_modules/@sit-devex-test-org/cowsays-be-safe/package.json ./public
          cp node_modules/@sit-devex-test-org/cowsays-be-safe/dist/bundle.js ./public

      - name: Add publication date
        run: |
          sed -i "s|PLACEHOLDER_DATE|$(date)|g" ./public/index.html

      # Step 3: Deploy to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.MASTERKEY }}
          publish_dir: ./public # Directory containing the files to deploy
          publish_branch: gh-pages
