name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  conf:
    runs-on: ubuntu-latest
    outputs:
      tag-version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${TAG#v}" >> ${GITHUB_OUTPUT}

  publish-package:
    uses: ./.github/workflows/.publish.yml
    needs: conf
    permissions:
      packages: write
      contents: write
    secrets: inherit
    with:
      version: ${{ needs.conf.outputs.tag-version }}

  release:
    runs-on: ubuntu-latest
    needs: [conf, publish-package]
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install published package
        run: npm install @sit-devex-test-org/cowsays-be-safe@${VERSION} --registry=https://npm.pkg.github.com
        env:
          VERSION: ${{ needs.conf.outputs.tag-version }}

      - name: Show script
        run: |
          cat node_modules/@sit-devex-test-org/cowsays-be-safe/package.json
          cat node_modules/@sit-devex-test-org/cowsays-be-safe/dist/bundle.js
