name: Push2main

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy:
    uses: ./.github/workflows/.deploy.yml
    needs: [conf, publish-package, release]
    permissions: {}
    secrets: inherit
