name: Deploy to gh-pages

on:
  push:
    branches:
      - main # Trigger this action when pushing to the main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: protected-gh-pages-env # Specify the environment to use

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (optional, if you need to build something)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: public
        run: npm install

      - name: Build project
        working-directory: public
        run: npx webpack

      # Step 3: Deploy to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          publish_dir: ./public # Directory containing the files to deploy
          publish_branch: gh-pages
